### ISSUE TITLE
Function as station error

### ISSUE THREAD

**Issue by mohog** [MuratovAS/gps-ntp-eth-esp32#2]
Looks like you have a minor error:

// Wifi.
    #ifdef OPERATE_AS_AP
    // Stand-alone access point.
    WiFi.disconnect(true); // This re-initialises the wifi.
    WiFi.softAP(ssid, ssid, CHANNEL, HIDE_SSID, MAX_CONNECTION);
    #endif

Looks like it should be:
// Wifi.
    #ifdef OPERATE_AS_AP
    // Stand-alone access point.
    WiFi.disconnect(true); // This re-initialises the wifi.
    WiFi.softAP(ssid, pass, CHANNEL, HIDE_SSID, MAX_CONNECTION);
    #endif

**Comment by MuratovAS** [comment]
Thank you. Corrected.
I have not used this mode just right :)
